sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
- ./mvnw install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- ./docs/src/main/asciidoc/ghpages.sh
script:
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./mvnw -s .settings.xml deploy -P release -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || ./mvnw install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: ebyeRdLvcMEhxeAcXjHb6s8+Gr7R9W4PDcSLEIxviZQgTQd3BM/ODNEkrKDfyE1IfIaTznit+A6qxXCjxVrsHXYn8yiEVGFMp+2ijo+e7K7VSbRXBtIfDMzELOZJ7+zIiLdDdwP/9wNGNOSe7q/wChBOuqLh2VCYngcof1ZVSxQ=
